(ns jinteki.chimera
  (:require
   [game.core.card :refer [agenda? corp? identity? runner?]]
   [jinteki.cards :refer [all-cards]]))

(def runner-econ-list
  #{"Bravado"
    "Carpe Diem"
    "Clean Getaway"
    "Creative Commission"
    "Day Job"
    "Dirty Laundry"
    "Easy Mark"
    "Guinea Pig"
    "Hot Pursuit"
    "Lucky Find"
    "Moshing"
    "Peace in Our Time"
    "Raindrops Cut Stone"
    "Strike Fund"
    "Sure Gamble"
    "Aesop's Pawnshop"
    "Armitage Codebusting"
    "Bank Job"
    "Beth Kilrain-Chang"
    "Crowdfunding"
    "Daily Casts"
    "DreamNet"
    "Info Bounty"
    "Jackpot!"
    "Liberated Account"
    "No Free Lunch"
    "Open Market"
    "Paladin Poemu"
    "Red Team"
    "Rogue Trading"
    "Security Testing"
    "Side Hustle"
    "Smartware Distributor"
    "Symmetrical Visage"
    "Telework Contract"
    "Tri-maf Contact"
    "Zona Sul Shipping"
    "Bankroll"
    "Fermenter"
    "Rezeki"
    "Tapwrm"
    })

(def runner-bans
  #{"Blackmail"
    "Calling in Favors"
    "Charm Offensive"
    "Data Breach"
    "Diana's Hunt"
    "Direct Access"
    "Employee Strike"
    "Eureka!"
    "Exclusive Party"
    "Exploratory Romp"
    "Fear the Masses"
    "Feint"
    "Government Investigations"
    "Immolation Script"
    "Itinerant Protesters"
    "Leverage"
    "Mars for Martians"
    "Mass Install"
    "Networking"
    "Office Supplies"
    "Paper Tripping"
    "Populist Rally"
    "Power Nap"
    "Rebirth"
    "Reboot"
    "Spree"
    "Surge"
    "Traffic Jam"
    "Uninstall"
    "Watch the World Burn"
    "Acacia"
    "Archives Interface"
    "BMI Buffer"
    "Bookmark"
    "Capstone"
    "Capybara"
    "Deep Red"
    "Dorm Computer"
    "Ekomind"
    "Forger"
    "Friday Chip"
    "Jeitinho"
    "LLDS Processor"
    "MemStrips"
    "Monolith"
    "Mu Safecracker"
    "Muresh Bodysuit"
    "Plascrete Carapace"
    "Public Terminal"
    "Qianju PT"
    "Rabbit Hole"
    "Ramujan-reliant 550 BMI"
    "Recon Drone"
    "Replicator"
    "Security Chip"
    "Titanium Ribs"
    "Unregistered S&W '35"
    "Window"
    "\"Pretty\" Mary da Silva"
    "Activist Support"
    "Adjusted Chronotype"
    "Akshara Sareen"
    "Angel Arena"
    "Assimilator"
    "Avgustina Ivanovskaya"
    "Bazaar"
    "Bio-Modeled Network"
    "Chrome Parlor"
    "Citadel Sanctuary"
    "Cookbook"
    "Counter Surveillance"
    "Crash Space"
    "Daeg, First Net-Cat"
    "Debbie \"Downtown\" Moreira"
    "Decoy"
    "District 99"
    "Donut Taganes"
    "Dr. Lovegood"
    "Environmental Testing"
    "Fester"
    "First Responders"
    "Gene Conditioning Shoppe"
    "Globalsec Security Clearance"
    "Investigative Journalism"
    "Investigator Inez Delgado"
    "Investigator Inez Delgado 2"
    "Investigator Inez Delgado 3"
    "Investigator Inez Delgado 4"
    "Jarogniew Mercs"
    "Keros Mcintyre"
    "Liberated Chela"
    "Motivation"
    "Net Mercur"
    "New Angeles City Hall"
    "Off-Campus Apartment"
    "Order of Sol"
    "Paige Piper"
    "Paparazzi"
    "Power Tap"
    "Public Sympathy"
    "Sacrificial Clone"
    "Shadow Team"
    "Starlight Crusade Funding"
    "Synthetic Blood"
    "Tallie Perrault"
    "The Back"
    "The Nihilist"
    "Thunder Art Gallery"
    "Underworld Contact"
    "Urban Art Vernissage"
    "Valentina Ferreira Carvalho"
    "Virus Breeding Ground"
    "Wasteland"
    "Whistleblower"
    "Wireless Net Pavilion"
    "Blackstone"
    "Crowbar"
    "Dagger"
    "Dai V"
    "Eater"
    "Fawkes"
    "Houdini"
    "Matryoshka"
    "Penrose"
    "Refractor"
    "Sage"
    "Shiv"
    "Spike"
    "Switchblade"
    "Umbrella"
    "Au Revoir"
    "Copycat"
    "Disrupter"
    "Flux Capacitor"
    "Heliamphora"
    "Hivemind"
    "Incubator"
    "Ixodidae"
    "Keyhole"
    "LLDS Energy Regulator"
    "Net Shield"
    "Origami"
    "Panchatantra"
    "Pawn"
    "Plague"
    "Progenitor"
    "Surveillance Network Key"
    "Surveillance Network Key 2"
    })

(def corp-bans
  #{"Ad Blitz"
    "Aimor"
    "Ancestral Imager"
    "Anson Rose"
    "Aryabhata Tech"
    "Awakening Center"
    "Back Channels"
    "Backroom Machinations"
    "Bad Times"
    "Bamboo Dome"
    "Big Brother"
    "Bioroid Efficiency Research"
    "Bioroid Work Crew"
    "Blacklist"
    "Bloom"
    "Bloodletter"
    "Bloop"
    "Brain-Taping Warehouse"
    "Broadcast Square"
    "Builder"
    "Bullfrog"
    "Burke Bugs"
    "Business As Usual"
    "Cerebral Static"
    "Cell Portal"
    "Chairman Hiro"
    "ChiLo City Grid"
    "CFC Excavation Contract"
    "Chronos Project"
    "Clyde Van Rite"
    "Cold Site Server"
    "Commercialization"
    "Constellation Protocol"
    "Corporate War"
    "Cyberdex Trial"
    "Dedicated Response Team"
    "Dedication Ceremony"
    "Defective Brainchips"
    "Director Haas"
    "Drone Screen"
    "Early Premiere"
    "Encrypted Portals"
    "Enforced Curfew"
    "Executive Retreat"
    "Fast Break"
    "Firmware Updates"
    "Foxfire"
    "Freelancer"
    "Fumiko Yamamori"
    "Fractal Threat Matrix"
    "Freedom of Information"
    "Gemini"
    "Henry Phillips"
    "Hasty Relocation"
    "Helium-3 Deposit"
    "Hellion Alpha Test"
    "Hollywood Renovation"
    "Howler"
    "Hudson 1.0"
    "Hyoubu Research Facility"
    "Illicit Sales"
    "Improved Protein Source"
    "Improved Tracers"
    "Increased Drop Rates"
    "Ireress"
    "Investigator Inez Delgado A"
    "Investigator Inez Delgado A 2"
    "Lakshmi Smartfabrics"
    "Lt. Todachine 2"
    "Lockdown"
    "Macrophage"
    "Mark Yale"
    "MCA Informant"
    "Medical Breakthrough"
    "Megaprix Qualifier"
    "Merlin"
    "Metamorph"
    "Merger"
    "Midnight-3 Arcology"
    "Midori"
    "Minelayer"
    "Mumbad Construction Co."
    "Net Analytics"
    "Net Police"
    "Net Quarantine"
    "Net Watchlist"
    "New Construction"
    "NEXT Wave 2"
    "Observe and Destroy"
    "Otoroshi"
    "PAD Factory"
    "Paper Trail"
    "Pachinko"
    "Personality Profiles"
    "Primary Transmission Dish"
    "Priority Construction"
    "Product Recall"
    "Project Ares"
    "Project Wotan"
    "Psychographics"
    "Puppet Master"
    "Ravana 1.0"
    "Rebranding Team"
    "Reconstruction Contract"
    "Regulatory Capture"
    "Remote Data Farm"
    "Research Grant"
    "Restoring Face"
    "Rutherford Grid"
    "Sacrifice"
    "Salvage"
    "Salem's Hospitality"
    "Satellite Grid"
    "Sealed Vault"
    "Searchlight"
    "Self-Destruct Chips"
    "Sentinel Defense Program"
    "Shipment from Kaguya"
    "Shoot the Moon"
    "Signal Jamming"
    "Simone Diego"
    "Snatch and Grab"
    "Space Camp"
    "Storgotic Resonator"
    "Student Loans"
    "Subcontract"
    "Success"
    "Sunset"
    "Superior Cyberwalls"
    "Synth DNA Modification"
    "Test Ground"
    "The Board"
    "The News Now Hour"
    "The Twins"
    "Tori Hanzō"
    "Traffic Accident"
    "Trieste Model Bioroids"
    "Trojan"
    "Tyr's Hand"
    "Tyrant"
    "Underway Grid"
    "Underway Renovation"
    "Upayoga"
    "Vulcan Coverup"
    "Victoria Jenkins"
    "Warden Fatuma"
    "Watchdog"
    "Wendigo"
    "Wetwork Refit"
    "Witness Tampering"
    "Woodcutter"
    "Zed 1.0"
    })

(def etr-ice
  #{"Afshar"
    "Bastion"
    "Battlement"
    "Capacitor"
    "Chimera"
    "Enigma"
    "Guard"
    "Hortum"
    "Ice Wall"
    "Magnet"
    "Maskirovka"
    "Meru Mati"
    "NEXT Bronze"
    "NEXT Silver"
    "Palisade"
    "Paper Wall"
    "Ping"
    "Quandary"
    "Quicksand"
    "Rainbow"
    "Sandstone"
    "Seidr Adaptive Barrier"
    "Self-Adapting Code Wall"
    "Spiderweb"
    "Tree Line"
    "Vanilla"
    "Wall of Static"
    "Wraparound"
    })

(def corp-econ-list
  #{"Adonis Campaign"
    "Anthill Excavation Contract"
    "Capital Investors"
    "Charlotte Caçador"
    "Cohort Guidance Program"
    "Commercial Bankers Group"
    "Daily Quest"
    "GRNDL Refinery"
    "Humanoid Resources"
    "Illegal Arms Factory"
    "Indian Union Stock Exchange"
    "Janaína \"JK\" Dumont Kindelán"
    "Launch Campaign"
    "Long-Term Investment"
    "Marilyn Campaign"
    "Marked Accounts"
    "Melange Mining Corp."
    "Mental Health Clinic"
    "Mumba Temple"
    "Nanoetching Matrix"
    "NASX"
    "NGO Front"
    "Nico Campaign"
    "Otto Campaign"
    "PAD Campaign"
    "Public Access Plaza"
    "Rashida Jaheem"
    "Refuge Campaign"
    "Regolith Mining License"
    "Roughneck Repair Squad"
    "Tiered Subscription"
    "Ubiquitous Vig"
    "Wall to Wall"
    "Attitude Adjustment"
    "Beanstalk Royalties"
    "Blue Level Clearance"
    "Celebrity Gift"
    "Extract"
    "Government Subsidy"
    "Greasing the Palm"
    "Green Level Clearance"
    "Hansei Review"
    "Hedge Fund"
    "IPO"
    "Lateral Growth"
    "Mindscaping"
    "Nonequivalent Exchange"
    "Paywall Implementation"
    "Peer Review"
    "Petty Cash"
    "Predictive Planogram"
    "Restructure"
    "Sweeps Week"
    "Too Big to Fail"
    "Tranquility Home Grid"
    "Congratulations!"
    "Pop-up Window"
    "Loot Box"
    "Special Offer"
    })

(defn make-runner-deck
  []
  (let [runner-cards (filter runner? (vals @all-cards))
        format-cards (filter #(and (not (runner-bans (:title %)))
                                   (not (#{"Peacock" "Aurora" "Creeper"} (:title %)))
                                   (not (identity? %)))
                             runner-cards)
        ;; runner has three base programs
        base-programs [{:title "Peacock"} {:title "Aurora"} {:title "Creeper"}]
        ;; runner has 8 base econ cards
        all-econ-cards (filter #(runner-econ-list (:title %)) runner-cards)
        chosen-econ-cards (take 8 (shuffle all-econ-cards))
        ;; runner has 29 random cards
        remaining-pool (filter #(not ((set (map :title (concat base-programs chosen-econ-cards)))
                                      (:title %)))
                               format-cards)
        remaining-cards (take 29 (shuffle remaining-pool))
        runner-deck (concat base-programs chosen-econ-cards remaining-cards)]
    {:identity {:title "Nova Initiumia: Catalyst & Impetus" :side "Runner" :code 33093}
     :name "Chimera Runner"
     :format "Chimera"
     :cards (mapv (fn [c] {:qty 1 :card (:title c)}) runner-deck)}))

(defn make-corp-deck
  []
  ;; recipe for a corp deck:
  (let [corp-cards (filter corp? (vals @all-cards))
        format-cards (filter #(and (not (corp-bans (:title %)))
                                   (not (identity? %)))
                             corp-cards)
        ;; 20 agenda points
        all-agendas (filter agenda? format-cards)
        points-value (fn [cards] (apply + (map :agendapoints cards)))
        chosen-agendas (reduce (fn [agendas agenda]
                                 (let [next (conj agendas agenda)]
                                   (cond
                                     (= 20 (points-value next)) (reduced next)
                                     (< (points-value next) 20) next
                                     :else agendas)))
                               []
                               (shuffle all-agendas))
        ;; 9 econ cards
        all-econ-cards (filter #(corp-econ-list (:title %)) corp-cards)
        chosen-econ-cards (take 9 (shuffle all-econ-cards))
        ;; 3 etr ice
        chosen-etr-ice (take 3 (shuffle (filter #(etr-ice (:title %)) corp-cards)))
        ;; fill until 49 cards
        to-fill (- 49 (+ 3 9 (count chosen-agendas)))
        remaining-pool (filter #(not ((set (map :title (concat chosen-agendas chosen-econ-cards chosen-etr-ice))) (:title %)))
                               (filter (complement agenda?) format-cards))
        remaining-cards (take to-fill (shuffle remaining-pool))
        corp-deck (concat chosen-agendas chosen-econ-cards chosen-etr-ice remaining-cards)]
    {:identity {:title "Ampère: Cybernetics For Anyone" :side "Corp" :code 33128}
     :name "Chimera Corp"
     :format "Chimera"
     :cards (mapv (fn [c] {:qty 1 :card (:title c)}) corp-deck)}))
