// Generated using http://www.dotnetwise.com/Code/Externs/index.html

var $ = {
    "fn": {
        "init": function () {},
        "selector": {},
        "jquery": {},
        "size": function () {},
        "get": function () {},
        "pushStack": function () {},
        "setArray": function () {},
        "each": function () {},
        "index": function () {},
        "attr": function () {},
        "css": function () {},
        "text": function () {},
        "wrapAll": function () {},
        "wrapInner": function () {},
        "wrap": function () {},
        "append": function () {},
        "prepend": function () {},
        "before": function () {},
        "after": function () {},
        "end": function () {},
        "push": function () {},
        "sort": function () {},
        "splice": function () {},
        "find": function () {},
        "clone": function () {},
        "filter": function () {},
        "closest": function () {},
        "not": function () {},
        "add": function () {},
        "is": function () {},
        "hasClass": function () {},
        "val": function () {},
        "html": function () {},
        "replaceWith": function () {},
        "eq": function () {},
        "slice": function () {},
        "map": function () {},
        "andSelf": function () {},
        "domManip": function () {},
        "extend": function () {},
        "parent": function () {},
        "parents": function () {},
        "next": function () {},
        "prev": function () {},
        "nextAll": function () {},
        "prevAll": function () {},
        "siblings": function () {},
        "children": function () {},
        "contents": function () {},
        "appendTo": function () {},
        "prependTo": function () {},
        "insertBefore": function () {},
        "insertAfter": function () {},
        "replaceAll": function () {},
        "removeAttr": function () {},
        "addClass": function () {},
        "removeClass": function () {},
        "toggleClass": function () {},
        "remove": function () {},
        "empty": function () {},
        "data": function () {},
        "removeData": function () {},
        "queue": function () {},
        "dequeue": function () {},
        "bind": function () {},
        "one": function () {},
        "unbind": function () {},
        "trigger": function () {},
        "triggerHandler": function () {},
        "toggle": function () {},
        "hover": function () {},
        "ready": function () {},
        "live": function () {},
        "die": function () {},
        "blur": function () {},
        "focus": function () {},
        "load": function () {},
        "resize": function () {},
        "scroll": function () {},
        "unload": function () {},
        "click": function () {},
        "dblclick": function () {},
        "mousedown": function () {},
        "mouseup": function () {},
        "mousemove": function () {},
        "mouseover": function () {},
        "mouseout": function () {},
        "mouseenter": function () {},
        "mouseleave": function () {},
        "change": function () {},
        "select": function () {},
        "submit": function () {},
        "keydown": function () {},
        "keypress": function () {},
        "keyup": function () {},
        "error": function () {},
        "_load": function () {},
        "serialize": function () {},
        "serializeArray": function () {},
        "ajaxStart": function () {},
        "ajaxStop": function () {},
        "ajaxComplete": function () {},
        "ajaxError": function () {},
        "ajaxSuccess": function () {},
        "ajaxSend": function () {},
        "show": function () {},
        "hide": function () {},
        "_toggle": function () {},
        "fadeTo": function () {},
        "animate": function () {},
        "stop": function () {},
        "slideDown": function () {},
        "slideUp": function () {},
        "slideToggle": function () {},
        "fadeIn": function () {},
        "fadeOut": function () {},
        "offset": function () {},
        "position": function () {},
        "offsetParent": function () {},
        "scrollLeft": function () {},
        "scrollTop": function () {},
        "innerHeight": function () {},
        "outerHeight": function () {},
        "height": function () {},
        "innerWidth": function () {},
        "outerWidth": function () {},
        "width": function () {},
        "disableSelection": function () {},
        "enableSelection": function () {},
        "emulateTransitionEnd": function () {},
        "alert": function () {}
    },
    "extend": function () {},
    "noConflict": function () {},
    "isFunction": function () {},
    "isArray": function () {},
    "isXMLDoc": function () {},
    "globalEval": function () {},
    "nodeName": function () {},
    "each": function () {},
    "prop": function () {},
    "className": {
        "add": function () {},
        "remove": function () {},
        "has": function () {}
    },
    "swap": function () {},
    "css": function () {},
    "curCSS": function () {},
    "clean": function () {},
    "attr": function () {},
    "trim": function () {},
    "makeArray": function () {},
    "inArray": function () {},
    "merge": function () {},
    "unique": function () {},
    "grep": function () {},
    "map": function () {},
    "browser": {
        "version": {},
        "safari": {},
        "opera": {},
        "msie": {},
        "mozilla": {}
    },
    "cache": {
        "1": {
            "events": {
                "unload": {
                    "1": function () {}
                },
                "load": {
                    "2": function () {}
                }
            },
            "handle": function () {}
        },
        "2": function () {},
        "4": function () {},
        "5": function () {}
    },
    "data": function () {},
    "removeData": function () {},
    "queue": function () {},
    "dequeue": function () {},
    "find": function () {},
    "filter": function () {},
    "expr": {
        "order": {
            "0": {},
            "1": {},
            "2": {},
            "3": {}
        },
        "match": {
            "ID": function () {},
            "CLASS": function () {},
            "NAME": function () {},
            "ATTR": function () {},
            "TAG": function () {},
            "CHILD": function () {},
            "POS": function () {},
            "PSEUDO": function () {}
        },
        "attrMap": {
            "class": {},
            "for": {}
        },
        "attrHandle": {
            "href": function () {}
        },
        "relative": {
            "+": function () {},
            ">": function () {},
            "": function () {},
            "~": function () {}
        },
        "find": {
            "ID": function () {},
            "NAME": function () {},
            "TAG": function () {},
            "CLASS": function () {}
        },
        "preFilter": {
            "CLASS": function () {},
            "ID": function () {},
            "TAG": function () {},
            "CHILD": function () {},
            "ATTR": function () {},
            "PSEUDO": function () {},
            "POS": function () {}
        },
        "filters": {
            "enabled": function () {},
            "disabled": function () {},
            "checked": function () {},
            "selected": function () {},
            "parent": function () {},
            "empty": function () {},
            "has": function () {},
            "header": function () {},
            "text": function () {},
            "radio": function () {},
            "checkbox": function () {},
            "file": function () {},
            "password": function () {},
            "submit": function () {},
            "image": function () {},
            "reset": function () {},
            "button": function () {},
            "input": function () {},
            "hidden": function () {},
            "visible": function () {},
            "animated": function () {},
            "data": function () {}
        },
        "setFilters": {
            "first": function () {},
            "last": function () {},
            "even": function () {},
            "odd": function () {},
            "lt": function () {},
            "gt": function () {},
            "nth": function () {},
            "eq": function () {}
        },
        "filter": {
            "PSEUDO": function () {},
            "CHILD": function () {},
            "ID": function () {},
            "TAG": function () {},
            "CLASS": function () {},
            "ATTR": function () {},
            "POS": function () {}
        },
        ":": {
            "enabled": function () {},
            "disabled": function () {},
            "checked": function () {},
            "selected": function () {},
            "parent": function () {},
            "empty": function () {},
            "has": function () {},
            "header": function () {},
            "text": function () {},
            "radio": function () {},
            "checkbox": function () {},
            "file": function () {},
            "password": function () {},
            "submit": function () {},
            "image": function () {},
            "reset": function () {},
            "button": function () {},
            "input": function () {},
            "hidden": function () {},
            "visible": function () {},
            "animated": function () {},
            "data": function () {}
        }
    },
    "multiFilter": function () {},
    "dir": function () {},
    "nth": function () {},
    "sibling": function () {},
    "event": {
        "add": function () {},
        "guid": {},
        "global": {
            "unload": {},
            "load": {},
            "scriptload": {}
        },
        "remove": function () {},
        "trigger": function () {},
        "handle": function () {},
        "props": {
            "0": {},
            "1": {},
            "2": {},
            "3": {},
            "4": {},
            "5": {},
            "6": {},
            "7": {},
            "8": {},
            "9": {},
            "10": {},
            "11": {},
            "12": {},
            "13": {},
            "14": {},
            "15": {},
            "16": {},
            "17": {},
            "18": {},
            "19": {},
            "20": {},
            "21": {},
            "22": {},
            "23": {},
            "24": {},
            "25": {},
            "26": {},
            "27": {},
            "28": {},
            "29": {},
            "30": {},
            "31": {},
            "32": {},
            "33": {}
        },
        "fix": function () {},
        "proxy": function () {},
        "special": {
            "ready": {
                "setup": function () {},
                "teardown": function () {}
            },
            "mouseenter": {
                "setup": function () {},
                "teardown": function () {}
            },
            "mouseleave": {
                "setup": function () {},
                "teardown": function () {}
            }
        },
        "specialAll": {
            "live": {
                "setup": function () {},
                "teardown": function () {}
            }
        },
        "triggered": {}
    },
    "Event": function () {},
    "isReady": {},
    "readyList": function () {},
    "ready": function () {},
    "support": {
        "leadingWhitespace": {},
        "tbody": {},
        "objectAll": {},
        "htmlSerialize": {},
        "style": {},
        "hrefNormalized": {},
        "opacity": {},
        "cssFloat": {},
        "scriptEval": {},
        "noCloneEvent": {},
        "boxModel": {},
        "transition": {
            "end": {}
        }
    },
    "props": {
        "for": {},
        "class": {},
        "float": {},
        "cssFloat": {},
        "styleFloat": {},
        "readonly": {},
        "maxlength": {},
        "cellspacing": {},
        "rowspan": {},
        "tabindex": {}
    },
    "get": function () {},
    "getScript": function () {},
    "getJSON": function () {},
    "post": function () {},
    "ajaxSetup": function () {},
    "ajaxSettings": {
        "url": {},
        "global": {},
        "type": {},
        "contentType": {},
        "processData": {},
        "async": {},
        "xhr": function () {},
        "accepts": {
            "xml": {},
            "html": {},
            "script": {},
            "json": {},
            "text": {},
            "_default": {}
        }
    },
    "lastModified": function () {},
    "ajax": function () {},
    "handleError": function () {},
    "active": {},
    "httpSuccess": function () {},
    "httpNotModified": function () {},
    "httpData": function () {},
    "param": function () {},
    "speed": function () {},
    "easing": {
        "linear": function () {},
        "swing": function () {}
    },
    "timers": function () {},
    "fx": function () {},
    "offset": {
        "initialize": function () {},
        "bodyOffset": function () {}
    },
    "xLazyLoader": function () {},
    "boxModel": {},
    "ui": {
        "version": {},
        "position": {
            "fit": {
                "left": function () {},
                "top": function () {}
            },
            "flip": {
                "left": function () {},
                "top": function () {}
            },
            "flipfit": {
                "left": function () {},
                "top": function () {}
            }
        }
    },
    "cleanData": function () {},
    "widget": function () {},
    "Widget": function () {},
    "position": {
        "scrollbarWidth": function () {},
        "getScrollInfo": function () {},
        "getWithinInfo": function () {}
    },
    "effects": {
        "effect": function () {}
    },
    "Color": function () {}
};

var ga = function() {};

var io = {
    "managers": function () {},
    "protocol": {},
    "connect": function () {},
    "Manager": function () {},
    "Socket": function () {}
};

var jQuery = {
    "fn": {
        "init": function () {},
        "selector": {},
        "jquery": {},
        "size": function () {},
        "get": function () {},
        "pushStack": function () {},
        "setArray": function () {},
        "each": function () {},
        "index": function () {},
        "attr": function () {},
        "css": function () {},
        "text": function () {},
        "wrapAll": function () {},
        "wrapInner": function () {},
        "wrap": function () {},
        "append": function () {},
        "prepend": function () {},
        "before": function () {},
        "after": function () {},
        "end": function () {},
        "push": function () {},
        "sort": function () {},
        "splice": function () {},
        "find": function () {},
        "clone": function () {},
        "filter": function () {},
        "closest": function () {},
        "not": function () {},
        "add": function () {},
        "is": function () {},
        "hasClass": function () {},
        "val": function () {},
        "html": function () {},
        "replaceWith": function () {},
        "eq": function () {},
        "slice": function () {},
        "map": function () {},
        "andSelf": function () {},
        "domManip": function () {},
        "extend": function () {},
        "parent": function () {},
        "parents": function () {},
        "next": function () {},
        "prev": function () {},
        "nextAll": function () {},
        "prevAll": function () {},
        "siblings": function () {},
        "children": function () {},
        "contents": function () {},
        "appendTo": function () {},
        "prependTo": function () {},
        "insertBefore": function () {},
        "insertAfter": function () {},
        "replaceAll": function () {},
        "removeAttr": function () {},
        "addClass": function () {},
        "removeClass": function () {},
        "toggleClass": function () {},
        "remove": function () {},
        "empty": function () {},
        "data": function () {},
        "removeData": function () {},
        "queue": function () {},
        "dequeue": function () {},
        "bind": function () {},
        "one": function () {},
        "unbind": function () {},
        "trigger": function () {},
        "triggerHandler": function () {},
        "toggle": function () {},
        "hover": function () {},
        "ready": function () {},
        "live": function () {},
        "die": function () {},
        "blur": function () {},
        "focus": function () {},
        "load": function () {},
        "resize": function () {},
        "scroll": function () {},
        "unload": function () {},
        "click": function () {},
        "dblclick": function () {},
        "mousedown": function () {},
        "mouseup": function () {},
        "mousemove": function () {},
        "mouseover": function () {},
        "mouseout": function () {},
        "mouseenter": function () {},
        "mouseleave": function () {},
        "change": function () {},
        "select": function () {},
        "submit": function () {},
        "keydown": function () {},
        "keypress": function () {},
        "keyup": function () {},
        "error": function () {},
        "_load": function () {},
        "serialize": function () {},
        "serializeArray": function () {},
        "ajaxStart": function () {},
        "ajaxStop": function () {},
        "ajaxComplete": function () {},
        "ajaxError": function () {},
        "ajaxSuccess": function () {},
        "ajaxSend": function () {},
        "show": function () {},
        "hide": function () {},
        "_toggle": function () {},
        "fadeTo": function () {},
        "animate": function () {},
        "stop": function () {},
        "slideDown": function () {},
        "slideUp": function () {},
        "slideToggle": function () {},
        "fadeIn": function () {},
        "fadeOut": function () {},
        "offset": function () {},
        "position": function () {},
        "offsetParent": function () {},
        "scrollLeft": function () {},
        "scrollTop": function () {},
        "innerHeight": function () {},
        "outerHeight": function () {},
        "height": function () {},
        "innerWidth": function () {},
        "outerWidth": function () {},
        "width": function () {},
        "disableSelection": function () {},
        "enableSelection": function () {},
        "emulateTransitionEnd": function () {},
        "alert": function () {}
    },
    "extend": function () {},
    "noConflict": function () {},
    "isFunction": function () {},
    "isArray": function () {},
    "isXMLDoc": function () {},
    "globalEval": function () {},
    "nodeName": function () {},
    "each": function () {},
    "prop": function () {},
    "className": {
        "add": function () {},
        "remove": function () {},
        "has": function () {}
    },
    "swap": function () {},
    "css": function () {},
    "curCSS": function () {},
    "clean": function () {},
    "attr": function () {},
    "trim": function () {},
    "makeArray": function () {},
    "inArray": function () {},
    "merge": function () {},
    "unique": function () {},
    "grep": function () {},
    "map": function () {},
    "browser": {
        "version": {},
        "safari": {},
        "opera": {},
        "msie": {},
        "mozilla": {}
    },
    "cache": {
        "1": {
            "events": {
                "unload": {
                    "1": function () {}
                },
                "load": {
                    "2": function () {}
                }
            },
            "handle": function () {}
        },
        "2": function () {},
        "4": function () {},
        "5": function () {}
    },
    "data": function () {},
    "removeData": function () {},
    "queue": function () {},
    "dequeue": function () {},
    "find": function () {},
    "filter": function () {},
    "expr": {
        "order": {
            "0": {},
            "1": {},
            "2": {},
            "3": {}
        },
        "match": {
            "ID": function () {},
            "CLASS": function () {},
            "NAME": function () {},
            "ATTR": function () {},
            "TAG": function () {},
            "CHILD": function () {},
            "POS": function () {},
            "PSEUDO": function () {}
        },
        "attrMap": {
            "class": {},
            "for": {}
        },
        "attrHandle": {
            "href": function () {}
        },
        "relative": {
            "+": function () {},
            ">": function () {},
            "": function () {},
            "~": function () {}
        },
        "find": {
            "ID": function () {},
            "NAME": function () {},
            "TAG": function () {},
            "CLASS": function () {}
        },
        "preFilter": {
            "CLASS": function () {},
            "ID": function () {},
            "TAG": function () {},
            "CHILD": function () {},
            "ATTR": function () {},
            "PSEUDO": function () {},
            "POS": function () {}
        },
        "filters": {
            "enabled": function () {},
            "disabled": function () {},
            "checked": function () {},
            "selected": function () {},
            "parent": function () {},
            "empty": function () {},
            "has": function () {},
            "header": function () {},
            "text": function () {},
            "radio": function () {},
            "checkbox": function () {},
            "file": function () {},
            "password": function () {},
            "submit": function () {},
            "image": function () {},
            "reset": function () {},
            "button": function () {},
            "input": function () {},
            "hidden": function () {},
            "visible": function () {},
            "animated": function () {},
            "data": function () {}
        },
        "setFilters": {
            "first": function () {},
            "last": function () {},
            "even": function () {},
            "odd": function () {},
            "lt": function () {},
            "gt": function () {},
            "nth": function () {},
            "eq": function () {}
        },
        "filter": {
            "PSEUDO": function () {},
            "CHILD": function () {},
            "ID": function () {},
            "TAG": function () {},
            "CLASS": function () {},
            "ATTR": function () {},
            "POS": function () {}
        },
        ":": {
            "enabled": function () {},
            "disabled": function () {},
            "checked": function () {},
            "selected": function () {},
            "parent": function () {},
            "empty": function () {},
            "has": function () {},
            "header": function () {},
            "text": function () {},
            "radio": function () {},
            "checkbox": function () {},
            "file": function () {},
            "password": function () {},
            "submit": function () {},
            "image": function () {},
            "reset": function () {},
            "button": function () {},
            "input": function () {},
            "hidden": function () {},
            "visible": function () {},
            "animated": function () {},
            "data": function () {}
        }
    },
    "multiFilter": function () {},
    "dir": function () {},
    "nth": function () {},
    "sibling": function () {},
    "event": {
        "add": function () {},
        "guid": {},
        "global": {
            "unload": {},
            "load": {},
            "scriptload": {}
        },
        "remove": function () {},
        "trigger": function () {},
        "handle": function () {},
        "props": {
            "0": {},
            "1": {},
            "2": {},
            "3": {},
            "4": {},
            "5": {},
            "6": {},
            "7": {},
            "8": {},
            "9": {},
            "10": {},
            "11": {},
            "12": {},
            "13": {},
            "14": {},
            "15": {},
            "16": {},
            "17": {},
            "18": {},
            "19": {},
            "20": {},
            "21": {},
            "22": {},
            "23": {},
            "24": {},
            "25": {},
            "26": {},
            "27": {},
            "28": {},
            "29": {},
            "30": {},
            "31": {},
            "32": {},
            "33": {}
        },
        "fix": function () {},
        "proxy": function () {},
        "special": {
            "ready": {
                "setup": function () {},
                "teardown": function () {}
            },
            "mouseenter": {
                "setup": function () {},
                "teardown": function () {}
            },
            "mouseleave": {
                "setup": function () {},
                "teardown": function () {}
            }
        },
        "specialAll": {
            "live": {
                "setup": function () {},
                "teardown": function () {}
            }
        },
        "triggered": {}
    },
    "Event": function () {},
    "isReady": {},
    "readyList": function () {},
    "ready": function () {},
    "support": {
        "leadingWhitespace": {},
        "tbody": {},
        "objectAll": {},
        "htmlSerialize": {},
        "style": {},
        "hrefNormalized": {},
        "opacity": {},
        "cssFloat": {},
        "scriptEval": {},
        "noCloneEvent": {},
        "boxModel": {},
        "transition": {
            "end": {}
        }
    },
    "props": {
        "for": {},
        "class": {},
        "float": {},
        "cssFloat": {},
        "styleFloat": {},
        "readonly": {},
        "maxlength": {},
        "cellspacing": {},
        "rowspan": {},
        "tabindex": {}
    },
    "get": function () {},
    "getScript": function () {},
    "getJSON": function () {},
    "post": function () {},
    "ajaxSetup": function () {},
    "ajaxSettings": {
        "url": {},
        "global": {},
        "type": {},
        "contentType": {},
        "processData": {},
        "async": {},
        "xhr": function () {},
        "accepts": {
            "xml": {},
            "html": {},
            "script": {},
            "json": {},
            "text": {},
            "_default": {}
        }
    },
    "lastModified": function () {},
    "ajax": function () {},
    "handleError": function () {},
    "active": {},
    "httpSuccess": function () {},
    "httpNotModified": function () {},
    "httpData": function () {},
    "param": function () {},
    "speed": function () {},
    "easing": {
        "linear": function () {},
        "swing": function () {}
    },
    "timers": function () {},
    "fx": function () {},
    "offset": {
        "initialize": function () {},
        "bodyOffset": function () {}
    },
    "xLazyLoader": function () {},
    "boxModel": {},
    "ui": {
        "version": {},
        "position": {
            "fit": {
                "left": function () {},
                "top": function () {}
            },
            "flip": {
                "left": function () {},
                "top": function () {}
            },
            "flipfit": {
                "left": function () {},
                "top": function () {}
            }
        }
    },
    "cleanData": function () {},
    "widget": function () {},
    "Widget": function () {},
    "position": {
        "scrollbarWidth": function () {},
        "getScrollInfo": function () {},
        "getWithinInfo": function () {}
    },
    "effects": {
        "effect": function () {}
    },
    "Color": function () {}
};

var marked = {
    "setOptions": function () {},
    "options": function () {},
    "defaults": {
        "gfm": {},
        "tables": {},
        "breaks": {},
        "pedantic": {},
        "sanitize": {},
        "sanitizer": function () {},
        "mangle": {},
        "smartLists": {},
        "silent": {},
        "highlight": function () {},
        "langPrefix": {},
        "smartypants": {},
        "headerPrefix": {},
        "renderer": {
            "options": function () {},
            "code": function () {},
            "blockquote": function () {},
            "html": function () {},
            "heading": function () {},
            "hr": function () {},
            "list": function () {},
            "listitem": function () {},
            "paragraph": function () {},
            "table": function () {},
            "tablerow": function () {},
            "tablecell": function () {},
            "strong": function () {},
            "em": function () {},
            "codespan": function () {},
            "br": function () {},
            "del": function () {},
            "link": function () {},
            "image": function () {},
            "text": function () {}
        },
        "xhtml": {}
    },
    "Parser": function () {},
    "parser": function () {},
    "Renderer": function () {},
    "Lexer": function () {},
    "lexer": function () {},
    "InlineLexer": function () {},
    "inlineLexer": function () {},
    "parse": function () {}
};

var moment = {
    "suppressDeprecationWarnings": {},
    "createFromInputFallback": function () {},
    "utc": function () {},
    "unix": function () {},
    "duration": function () {},
    "version": {},
    "defaultFormat": {},
    "momentProperties": {
        "_isAMomentObject": function () {},
        "_i": function () {},
        "_f": function () {},
        "_l": function () {},
        "_strict": function () {},
        "_isUTC": function () {},
        "_offset": function () {},
        "_pf": function () {},
        "_lang": function () {}
    },
    "updateOffset": function () {},
    "lang": function () {},
    "langData": function () {},
    "isMoment": function () {},
    "isDuration": function () {},
    "weekdaysMin": function () {},
    "weekdaysShort": function () {},
    "weekdays": function () {},
    "monthsShort": function () {},
    "months": function () {},
    "normalizeUnits": function () {},
    "invalid": function () {},
    "parseZone": function () {},
    "parseTwoDigitYear": function () {},
    "fn": {
        "clone": function () {},
        "valueOf": function () {},
        "unix": function () {},
        "toString": function () {},
        "toDate": function () {},
        "toISOString": function () {},
        "toArray": function () {},
        "isValid": function () {},
        "isDSTShifted": function () {},
        "parsingFlags": function () {},
        "invalidAt": function () {},
        "utc": function () {},
        "local": function () {},
        "format": function () {},
        "add": function () {},
        "subtract": function () {},
        "diff": function () {},
        "from": function () {},
        "fromNow": function () {},
        "calendar": function () {},
        "isLeapYear": function () {},
        "isDST": function () {},
        "day": function () {},
        "month": function () {},
        "startOf": function () {},
        "endOf": function () {},
        "isAfter": function () {},
        "isBefore": function () {},
        "isSame": function () {},
        "min": function () {},
        "max": function () {},
        "zone": function () {},
        "zoneAbbr": function () {},
        "zoneName": function () {},
        "parseZone": function () {},
        "hasAlignedHourOffset": function () {},
        "daysInMonth": function () {},
        "dayOfYear": function () {},
        "quarter": function () {},
        "weekYear": function () {},
        "isoWeekYear": function () {},
        "week": function () {},
        "isoWeek": function () {},
        "weekday": function () {},
        "isoWeekday": function () {},
        "isoWeeksInYear": function () {},
        "weeksInYear": function () {},
        "get": function () {},
        "set": function () {},
        "lang": function () {},
        "milliseconds": function () {},
        "millisecond": function () {},
        "seconds": function () {},
        "second": function () {},
        "minutes": function () {},
        "minute": function () {},
        "hours": function () {},
        "hour": function () {},
        "date": function () {},
        "dates": function () {},
        "year": function () {},
        "years": function () {},
        "days": function () {},
        "months": function () {},
        "weeks": function () {},
        "isoWeeks": function () {},
        "quarters": function () {},
        "toJSON": function () {},
        "_lang": {
            "ordinal": function () {},
            "_abbr": {},
            "set": function () {},
            "_months": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {},
                "7": {},
                "8": {},
                "9": {},
                "10": {},
                "11": {}
            },
            "months": function () {},
            "_monthsShort": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {},
                "7": {},
                "8": {},
                "9": {},
                "10": {},
                "11": {}
            },
            "monthsShort": function () {},
            "monthsParse": function () {},
            "_weekdays": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {}
            },
            "weekdays": function () {},
            "_weekdaysShort": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {}
            },
            "weekdaysShort": function () {},
            "_weekdaysMin": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {}
            },
            "weekdaysMin": function () {},
            "weekdaysParse": function () {},
            "_longDateFormat": {
                "LT": {},
                "L": {},
                "LL": {},
                "LLL": {},
                "LLLL": {}
            },
            "longDateFormat": function () {},
            "isPM": function () {},
            "_meridiemParse": function () {},
            "meridiem": function () {},
            "_calendar": {
                "sameDay": {},
                "nextDay": {},
                "nextWeek": {},
                "lastDay": {},
                "lastWeek": {},
                "sameElse": {}
            },
            "calendar": function () {},
            "_relativeTime": {
                "future": {},
                "past": {},
                "s": {},
                "m": {},
                "mm": {},
                "h": {},
                "hh": {},
                "d": {},
                "dd": {},
                "M": {},
                "MM": {},
                "y": {},
                "yy": {}
            },
            "relativeTime": function () {},
            "pastFuture": function () {},
            "_ordinal": {},
            "preparse": function () {},
            "postformat": function () {},
            "week": function () {},
            "_week": {
                "dow": {},
                "doy": {}
            },
            "_invalidDate": {},
            "invalidDate": function () {}
        }
    }
};

var React = {
    "Children": {
        "map": function () {},
        "forEach": function () {},
        "count": function () {},
        "toArray": function () {},
        "only": function () {}
    },
    "Component": function () {},
    "createElement": function () {},
    "cloneElement": function () {},
    "isValidElement": function () {},
    "PropTypes": {
        "array": function () {},
        "bool": function () {},
        "func": function () {},
        "number": function () {},
        "object": function () {},
        "string": function () {},
        "any": function () {},
        "arrayOf": function () {},
        "element": function () {},
        "instanceOf": function () {},
        "node": function () {},
        "objectOf": function () {},
        "oneOf": function () {},
        "oneOfType": function () {},
        "shape": function () {}
    },
    "createClass": function () {},
    "createFactory": function () {},
    "createMixin": function () {},
    "DOM": {
        "a": function () {},
        "abbr": function () {},
        "address": function () {},
        "area": function () {},
        "article": function () {},
        "aside": function () {},
        "audio": function () {},
        "b": function () {},
        "base": function () {},
        "bdi": function () {},
        "bdo": function () {},
        "big": function () {},
        "blockquote": function () {},
        "body": function () {},
        "br": function () {},
        "button": function () {},
        "canvas": function () {},
        "caption": function () {},
        "cite": function () {},
        "code": function () {},
        "col": function () {},
        "colgroup": function () {},
        "data": function () {},
        "datalist": function () {},
        "dd": function () {},
        "del": function () {},
        "details": function () {},
        "dfn": function () {},
        "dialog": function () {},
        "div": function () {},
        "dl": function () {},
        "dt": function () {},
        "em": function () {},
        "embed": function () {},
        "fieldset": function () {},
        "figcaption": function () {},
        "figure": function () {},
        "footer": function () {},
        "form": function () {},
        "h1": function () {},
        "h2": function () {},
        "h3": function () {},
        "h4": function () {},
        "h5": function () {},
        "h6": function () {},
        "head": function () {},
        "header": function () {},
        "hgroup": function () {},
        "hr": function () {},
        "html": function () {},
        "i": function () {},
        "iframe": function () {},
        "img": function () {},
        "input": function () {},
        "ins": function () {},
        "kbd": function () {},
        "keygen": function () {},
        "label": function () {},
        "legend": function () {},
        "li": function () {},
        "link": function () {},
        "main": function () {},
        "map": function () {},
        "mark": function () {},
        "menu": function () {},
        "menuitem": function () {},
        "meta": function () {},
        "meter": function () {},
        "nav": function () {},
        "noscript": function () {},
        "object": function () {},
        "ol": function () {},
        "optgroup": function () {},
        "option": function () {},
        "output": function () {},
        "p": function () {},
        "param": function () {},
        "picture": function () {},
        "pre": function () {},
        "progress": function () {},
        "q": function () {},
        "rp": function () {},
        "rt": function () {},
        "ruby": function () {},
        "s": function () {},
        "samp": function () {},
        "script": function () {},
        "section": function () {},
        "select": function () {},
        "small": function () {},
        "source": function () {},
        "span": function () {},
        "strong": function () {},
        "style": function () {},
        "sub": function () {},
        "summary": function () {},
        "sup": function () {},
        "table": function () {},
        "tbody": function () {},
        "td": function () {},
        "textarea": function () {},
        "tfoot": function () {},
        "th": function () {},
        "thead": function () {},
        "time": function () {},
        "title": function () {},
        "tr": function () {},
        "track": function () {},
        "u": function () {},
        "ul": function () {},
        "var": function () {},
        "video": function () {},
        "wbr": function () {},
        "circle": function () {},
        "clipPath": function () {},
        "defs": function () {},
        "ellipse": function () {},
        "g": function () {},
        "image": function () {},
        "line": function () {},
        "linearGradient": function () {},
        "mask": function () {},
        "path": function () {},
        "pattern": function () {},
        "polygon": function () {},
        "polyline": function () {},
        "radialGradient": function () {},
        "rect": function () {},
        "stop": function () {},
        "svg": function () {},
        "text": function () {},
        "tspan": function () {}
    },
    "version": {},
    "__spread": function () {},
    "findDOMNode": function () {},
    "render": function () {},
    "unmountComponentAtNode": function () {},
    "renderToString": function () {},
    "renderToStaticMarkup": function () {},
    "__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED": {
        "findDOMNode": function () {},
        "render": function () {},
        "unmountComponentAtNode": function () {},
        "version": {},
        "unstable_batchedUpdates": function () {},
        "unstable_renderSubtreeIntoContainer": function () {}
    },
    "__SECRET_DOM_SERVER_DO_NOT_USE_OR_YOU_WILL_BE_FIRED": {
        "renderToString": function () {},
        "renderToStaticMarkup": function () {},
        "version": {}
    }
};

var toastr = {
    "clear": function () {},
    "remove": function () {},
    "error": function () {},
    "getContainer": function () {},
    "info": function () {},
    "options": function () {},
    "subscribe": function () {},
    "success": function () {},
    "version": {},
    "warning": function () {}
};
