(ns game-test.cards.operations.subliminal-messaging
  (:require [game.core :as core]
            [game-test.core :refer :all]
            [game-test.utils :refer :all]
            [game-test.macros :refer :all]
            [clojure.test :refer :all]))

(deftest subliminal-messaging
  ;; Subliminal Messaging - Playing/trashing/milling will all prompt returning to hand
  (testing "Basic test"
    (do-game
      (new-game {:corp {:deck [(qty "Subliminal Messaging" 3)]}
                 :runner {:id "Noise: Hacker Extraordinaire"
                          :deck [(qty "Cache" 3) "Utopia Shard"]}})
      (play-from-hand state :corp "Subliminal Messaging")
      (is (= 6 (:credit (get-corp))))
      (is (= 3 (:click (get-corp))) "First Subliminal Messaging gains 1 click")
      (play-from-hand state :corp "Subliminal Messaging")
      (is (= 7 (:credit (get-corp))))
      (is (= 2 (:click (get-corp))) "Second Subliminal Messaging does not gain 1 click")
      (trash-from-hand state :corp "Subliminal Messaging")
      (is (zero? (count (:hand (get-corp)))))
      (take-credits state :corp)
      (take-credits state :runner)
      (click-prompt state :corp "Yes")
      (click-prompt state :corp "Yes")
      (click-prompt state :corp "Yes")
      (is (= 3 (count (:hand (get-corp)))) "All 3 Subliminals returned to HQ")
      (core/move state :corp (find-card "Subliminal Messaging" (:hand (get-corp))) :deck)
      (take-credits state :corp)
      (play-from-hand state :runner "Cache")
      (play-from-hand state :runner "Utopia Shard")
      (let [utopia (get-resource state 0)]
        (card-ability state :runner utopia 0))
      (take-credits state :runner)
      (click-prompt state :corp "Yes")
      (click-prompt state :corp "Yes")
      (click-prompt state :corp "Yes")
      (is (= 3 (count (:hand (get-corp)))) "All 3 Subliminals returned to HQ")
      (play-from-hand state :corp "Subliminal Messaging")
      (take-credits state :corp)
      (run-on state "R&D")
      (run-jack-out state)
      (take-credits state :runner)
      (is (empty? (get-in @state [:corp :prompt])) "No prompt here because runner made a run last turn")
      (take-credits state :corp)
      (is (= 2 (count (:hand (get-corp)))))
      (is (= 1 (count (:discard (get-corp)))) "1 Subliminal not returned because runner made a run last turn")))
  (testing "Scenario involving Subliminal being added to HQ with Archived Memories"
    (do-game
      (new-game {:corp {:deck [(qty "Subliminal Messaging" 2) "Archived Memories"]}})
      (play-from-hand state :corp "Subliminal Messaging")
      (play-from-hand state :corp "Subliminal Messaging")
      (play-from-hand state :corp "Archived Memories")
      (click-card state :corp (find-card "Subliminal Messaging" (:discard (get-corp))))
      (is (= 2 (count (:discard (get-corp)))))
      (is (= 1 (count (:hand (get-corp)))))
      (take-credits state :corp)
      (take-credits state :runner)
      (click-prompt state :corp "No")
      (is (empty? (get-in @state [:corp :prompt])) "Only 1 Subliminal prompt")
      (play-from-hand state :corp "Subliminal Messaging")
      (take-credits state :corp)
      (take-credits state :runner)
      (click-prompt state :corp "Yes")
      (click-prompt state :corp "Yes")
      (is (empty? (get-in @state [:corp :prompt]))
          "Only 2 Subliminal prompts - there will be a third if flag not cleared")))
  (testing "Scenario involving Subliminal being reshuffled into R&D with Jackson"
    (do-game
      (new-game {:corp {:deck ["Subliminal Messaging" "Jackson Howard"]}})
      (play-from-hand state :corp "Subliminal Messaging")
      (play-from-hand state :corp "Jackson Howard" "New remote")
      (take-credits state :corp)
      (let [jhow (get-content state :remote1 0)]
        (core/rez state :corp jhow)
        (card-ability state :corp jhow 1)
        (click-card state :corp (find-card "Subliminal Messaging" (:discard (get-corp))))
        (click-prompt state :corp "Done")
        (is (zero? (count (:discard (get-corp)))))
        (is (= 1 (count (:rfg (get-corp))))))
      (take-credits state :runner)
      (play-from-hand state :corp "Subliminal Messaging")
      (take-credits state :corp)
      (take-credits state :runner)
      (click-prompt state :corp "Yes")
      (is (= 1 (count (:hand (get-corp)))) "Subliminal returned to HQ")
      (is (empty? (get-in @state [:corp :prompt]))
          "Subliminal prompt cleared - there will be a second prompt if flag not cleared")))
  (testing "Runner made run, ensure game asks again next turn"
    (do-game
      (new-game {:corp {:deck [(qty "Subliminal Messaging" 2)]}})
      (play-from-hand state :corp "Subliminal Messaging")
      (trash-from-hand state :corp "Subliminal Messaging")
      (take-credits state :corp)
      (run-on state "R&D")
      (run-jack-out state)
      (take-credits state :runner)
      (is (empty? (get-in @state [:corp :prompt])) "No prompt here because runner made a run last turn")
      (take-credits state :corp)
      (take-credits state :runner)
      (click-prompt state :corp "Yes")
      (click-prompt state :corp "Yes")
      (is (= 2 (count (:hand (get-corp)))) "Both Subliminals returned to HQ")
      (is (zero? (count (:discard (get-corp)))) "No Subliminals in Archives")))
  (testing "User declines to return to hand, ensure game asks again next turn"
    (do-game
      (new-game {:corp {:deck [(qty "Subliminal Messaging" 2)]}})
      (play-from-hand state :corp "Subliminal Messaging")
      (trash-from-hand state :corp "Subliminal Messaging")
      (take-credits state :corp)
      (take-credits state :runner)
      (click-prompt state :corp "No")
      (click-prompt state :corp "No")
      (is (zero? (count (:hand (get-corp)))) "Neither Subliminal returned to HQ")
      (is (= 2 (count (:discard (get-corp)))) "Both Subliminals in Archives")
      (take-credits state :corp)
      (take-credits state :runner)
      (click-prompt state :corp "Yes")
      (click-prompt state :corp "Yes")
      (is (= 2 (count (:hand (get-corp)))) "Both Subliminals returned to HQ")
      (is (zero? (count (:discard (get-corp)))) "No Subliminals in Archives"))))
