/**********************************************************************
 * Extern for Howl
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Howl = function () {};
Howl.prototype = {
  "load": function () {},
  "urls": function () {},
  "play": function () {},
  "pause": function () {},
  "stop": function () {},
  "mute": function () {},
  "unmute": function () {},
  "volume": function () {},
  "loop": function () {},
  "sprite": function () {},
  "pos": function () {},
  "pos3d": function () {},
  "fade": function () {},
  "fadeIn": function () {},
  "fadeOut": function () {},
  "_nodeById": function () {},
  "_activeNode": function () {},
  "_inactiveNode": function () {},
  "_drainPool": function () {},
  "_clearEndTimer": function () {},
  "_setupAudioNode": function () {},
  "on": function () {},
  "off": function () {},
  "unload": function () {}
};
/**********************************************************************
 * End Generated Extern for Howl
/**********************************************************************/
