/**********************************************************************
 * Extern for Howl
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Howl = function () {};
Howl.prototype = {
  "_cleanBuffer": function () {},
  "_clearTimer": function () {},
  "_drain": function () {},
  "_emit": function () {},
  "_ended": function () {},
  "_getSoundIds": function () {},
  "_inactiveSound": function () {},
  "_loadQueue": function () {},
  "_refreshBuffer": function () {},
  "_soundById": function () {},
  "_startFadeInterval": function () {},
  "_stopFade": function () {},
  "duration": function () {},
  "fade": function () {},
  "init": function () {},
  "load": function () {},
  "loop": function () {},
  "mute": function () {},
  "off": function () {},
  "on": function () {},
  "once": function () {},
  "orientation": function () {},
  "pannerAttr": function () {},
  "pause": function () {},
  "play": function () {},
  "playing": function () {},
  "pos": function () {},
  "rate": function () {},
  "seek": function () {},
  "state": function () {},
  "stereo": function () {},
  "stop": function () {},
  "unload": function () {},
  "volume": function () {}
};
/**********************************************************************
 * End Generated Extern for Howl
/**********************************************************************/
