/**********************************************************************
 * Extern for marked
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var marked = {
  "setOptions": function () {},
  "options": function () {},
  "defaults": {
    "gfm": {},
    "tables": {},
    "breaks": {},
    "pedantic": {},
    "sanitize": {},
    "sanitizer": {},
    "mangle": {},
    "smartLists": {},
    "silent": {},
    "highlight": {},
    "langPrefix": {},
    "smartypants": {},
    "headerPrefix": {},
    "renderer": {
      "options": {},
      "code": function () {},
      "blockquote": function () {},
      "html": function () {},
      "heading": function () {},
      "hr": function () {},
      "list": function () {},
      "listitem": function () {},
      "paragraph": function () {},
      "table": function () {},
      "tablerow": function () {},
      "tablecell": function () {},
      "strong": function () {},
      "em": function () {},
      "codespan": function () {},
      "br": function () {},
      "del": function () {},
      "link": function () {},
      "image": function () {},
      "text": function () {}
    },
    "xhtml": {}
  },
  "Parser": {
    "parse": function () {}
  },
  "parser": function () {},
  "Renderer": function () {},
  "Lexer": {
    "rules": {
      "newline": {},
      "code": {},
      "fences": {
        "exec": function () {}
      },
      "hr": {},
      "heading": {},
      "nptable": {
        "exec": function () {}
      },
      "lheading": {},
      "blockquote": {},
      "list": {},
      "html": {},
      "def": {},
      "table": {
        "exec": function () {}
      },
      "paragraph": {},
      "text": {},
      "bullet": {},
      "item": {},
      "_tag": {},
      "normal": {
        "newline": {},
        "code": {},
        "fences": {
          "exec": function () {}
        },
        "hr": {},
        "heading": {},
        "nptable": {
          "exec": function () {}
        },
        "lheading": {},
        "blockquote": {},
        "list": {},
        "html": {},
        "def": {},
        "table": {
          "exec": function () {}
        },
        "paragraph": {},
        "text": {},
        "bullet": {},
        "item": {},
        "_tag": {}
      },
      "gfm": {
        "newline": {},
        "code": {},
        "fences": {},
        "hr": {},
        "heading": {},
        "nptable": {
          "exec": function () {}
        },
        "lheading": {},
        "blockquote": {},
        "list": {},
        "html": {},
        "def": {},
        "table": {
          "exec": function () {}
        },
        "paragraph": {},
        "text": {},
        "bullet": {},
        "item": {},
        "_tag": {}
      },
      "tables": {
        "newline": {},
        "code": {},
        "fences": {},
        "hr": {},
        "heading": {},
        "nptable": {},
        "lheading": {},
        "blockquote": {},
        "list": {},
        "html": {},
        "def": {},
        "table": {},
        "paragraph": {},
        "text": {},
        "bullet": {},
        "item": {},
        "_tag": {}
      }
    },
    "lex": function () {}
  },
  "lexer": function () {},
  "InlineLexer": {
    "rules": {
      "escape": {},
      "autolink": {},
      "url": {
        "exec": function () {}
      },
      "tag": {},
      "link": {},
      "reflink": {},
      "nolink": {},
      "strong": {},
      "em": {},
      "code": {},
      "br": {},
      "del": {
        "exec": function () {}
      },
      "text": {},
      "_inside": {},
      "_href": {},
      "normal": {
        "escape": {},
        "autolink": {},
        "url": {
          "exec": function () {}
        },
        "tag": {},
        "link": {},
        "reflink": {},
        "nolink": {},
        "strong": {},
        "em": {},
        "code": {},
        "br": {},
        "del": {
          "exec": function () {}
        },
        "text": {},
        "_inside": {},
        "_href": {}
      },
      "pedantic": {
        "escape": {},
        "autolink": {},
        "url": {
          "exec": function () {}
        },
        "tag": {},
        "link": {},
        "reflink": {},
        "nolink": {},
        "strong": {},
        "em": {},
        "code": {},
        "br": {},
        "del": {
          "exec": function () {}
        },
        "text": {},
        "_inside": {},
        "_href": {}
      },
      "gfm": {
        "escape": {},
        "autolink": {},
        "url": {},
        "tag": {},
        "link": {},
        "reflink": {},
        "nolink": {},
        "strong": {},
        "em": {},
        "code": {},
        "br": {},
        "del": {},
        "text": {},
        "_inside": {},
        "_href": {}
      },
      "breaks": {
        "escape": {},
        "autolink": {},
        "url": {},
        "tag": {},
        "link": {},
        "reflink": {},
        "nolink": {},
        "strong": {},
        "em": {},
        "code": {},
        "br": {},
        "del": {},
        "text": {},
        "_inside": {},
        "_href": {}
      }
    },
    "output": function () {}
  },
  "inlineLexer": function () {},
  "parse": {
    "setOptions": function () {},
    "options": function () {},
    "defaults": {
      "gfm": {},
      "tables": {},
      "breaks": {},
      "pedantic": {},
      "sanitize": {},
      "sanitizer": {},
      "mangle": {},
      "smartLists": {},
      "silent": {},
      "highlight": {},
      "langPrefix": {},
      "smartypants": {},
      "headerPrefix": {},
      "renderer": {
        "options": {},
        "code": function () {},
        "blockquote": function () {},
        "html": function () {},
        "heading": function () {},
        "hr": function () {},
        "list": function () {},
        "listitem": function () {},
        "paragraph": function () {},
        "table": function () {},
        "tablerow": function () {},
        "tablecell": function () {},
        "strong": function () {},
        "em": function () {},
        "codespan": function () {},
        "br": function () {},
        "del": function () {},
        "link": function () {},
        "image": function () {},
        "text": function () {}
      },
      "xhtml": {}
    },
    "Parser": {
      "parse": function () {}
    },
    "parser": function () {},
    "Renderer": function () {},
    "Lexer": {
      "rules": {
        "newline": {},
        "code": {},
        "fences": {
          "exec": function () {}
        },
        "hr": {},
        "heading": {},
        "nptable": {
          "exec": function () {}
        },
        "lheading": {},
        "blockquote": {},
        "list": {},
        "html": {},
        "def": {},
        "table": {
          "exec": function () {}
        },
        "paragraph": {},
        "text": {},
        "bullet": {},
        "item": {},
        "_tag": {},
        "normal": {
          "newline": {},
          "code": {},
          "fences": {
            "exec": function () {}
          },
          "hr": {},
          "heading": {},
          "nptable": {
            "exec": function () {}
          },
          "lheading": {},
          "blockquote": {},
          "list": {},
          "html": {},
          "def": {},
          "table": {
            "exec": function () {}
          },
          "paragraph": {},
          "text": {},
          "bullet": {},
          "item": {},
          "_tag": {}
        },
        "gfm": {
          "newline": {},
          "code": {},
          "fences": {},
          "hr": {},
          "heading": {},
          "nptable": {
            "exec": function () {}
          },
          "lheading": {},
          "blockquote": {},
          "list": {},
          "html": {},
          "def": {},
          "table": {
            "exec": function () {}
          },
          "paragraph": {},
          "text": {},
          "bullet": {},
          "item": {},
          "_tag": {}
        },
        "tables": {
          "newline": {},
          "code": {},
          "fences": {},
          "hr": {},
          "heading": {},
          "nptable": {},
          "lheading": {},
          "blockquote": {},
          "list": {},
          "html": {},
          "def": {},
          "table": {},
          "paragraph": {},
          "text": {},
          "bullet": {},
          "item": {},
          "_tag": {}
        }
      },
      "lex": function () {}
    },
    "lexer": function () {},
    "InlineLexer": {
      "rules": {
        "escape": {},
        "autolink": {},
        "url": {
          "exec": function () {}
        },
        "tag": {},
        "link": {},
        "reflink": {},
        "nolink": {},
        "strong": {},
        "em": {},
        "code": {},
        "br": {},
        "del": {
          "exec": function () {}
        },
        "text": {},
        "_inside": {},
        "_href": {},
        "normal": {
          "escape": {},
          "autolink": {},
          "url": {
            "exec": function () {}
          },
          "tag": {},
          "link": {},
          "reflink": {},
          "nolink": {},
          "strong": {},
          "em": {},
          "code": {},
          "br": {},
          "del": {
            "exec": function () {}
          },
          "text": {},
          "_inside": {},
          "_href": {}
        },
        "pedantic": {
          "escape": {},
          "autolink": {},
          "url": {
            "exec": function () {}
          },
          "tag": {},
          "link": {},
          "reflink": {},
          "nolink": {},
          "strong": {},
          "em": {},
          "code": {},
          "br": {},
          "del": {
            "exec": function () {}
          },
          "text": {},
          "_inside": {},
          "_href": {}
        },
        "gfm": {
          "escape": {},
          "autolink": {},
          "url": {},
          "tag": {},
          "link": {},
          "reflink": {},
          "nolink": {},
          "strong": {},
          "em": {},
          "code": {},
          "br": {},
          "del": {},
          "text": {},
          "_inside": {},
          "_href": {}
        },
        "breaks": {
          "escape": {},
          "autolink": {},
          "url": {},
          "tag": {},
          "link": {},
          "reflink": {},
          "nolink": {},
          "strong": {},
          "em": {},
          "code": {},
          "br": {},
          "del": {},
          "text": {},
          "_inside": {},
          "_href": {}
        }
      },
      "output": function () {}
    },
    "inlineLexer": function () {},
    "parse": function () {}
  }
};
marked.Parser.prototype = {
  "parse": function () {},
  "next": function () {},
  "peek": function () {},
  "parseText": function () {},
  "tok": function () {}
};
marked.Renderer.prototype = {
  "code": function () {},
  "blockquote": function () {},
  "html": function () {},
  "heading": function () {},
  "hr": function () {},
  "list": function () {},
  "listitem": function () {},
  "paragraph": function () {},
  "table": function () {},
  "tablerow": function () {},
  "tablecell": function () {},
  "strong": function () {},
  "em": function () {},
  "codespan": function () {},
  "br": function () {},
  "del": function () {},
  "link": function () {},
  "image": function () {},
  "text": function () {}
};
marked.Lexer.prototype = {
  "lex": function () {},
  "token": function () {}
};
marked.InlineLexer.prototype = {
  "output": function () {},
  "outputLink": function () {},
  "smartypants": function () {},
  "mangle": function () {}
};
marked.parse.Parser.prototype = {
  "parse": function () {},
  "next": function () {},
  "peek": function () {},
  "parseText": function () {},
  "tok": function () {}
};
marked.parse.Renderer.prototype = {
  "code": function () {},
  "blockquote": function () {},
  "html": function () {},
  "heading": function () {},
  "hr": function () {},
  "list": function () {},
  "listitem": function () {},
  "paragraph": function () {},
  "table": function () {},
  "tablerow": function () {},
  "tablecell": function () {},
  "strong": function () {},
  "em": function () {},
  "codespan": function () {},
  "br": function () {},
  "del": function () {},
  "link": function () {},
  "image": function () {},
  "text": function () {}
};
marked.parse.Lexer.prototype = {
  "lex": function () {},
  "token": function () {}
};
marked.parse.InlineLexer.prototype = {
  "output": function () {},
  "outputLink": function () {},
  "smartypants": function () {},
  "mangle": function () {}
};
/**********************************************************************
 * End Generated Extern for marked
/**********************************************************************/
