/**********************************************************************
 * Extern for toastr
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var toastr = {
  "clear": function () {},
  "remove": function () {},
  "error": function () {},
  "getContainer": function () {},
  "info": function () {},
  "options": {},
  "subscribe": function () {},
  "success": function () {},
  "version": {},
  "warning": function () {}
};
/**********************************************************************
 * End Generated Extern for toastr
/**********************************************************************/
